from enum import Enum

FPS = 60

TILE_SIZE = 16
WINDOW_SIZE = (42 * TILE_SIZE, 31 * TILE_SIZE)

LOADING_BAR_SIZE = (200, 25)

TILEID = Enum('TileID', ['VOID',
                         'PACGUM',
                         'POWER_PACGUM',
                         'FRUIT_CHERRY',
                         'FRUIT_STRAWBERRY',
                         'FRUIT_ORANGE',
                         'FRUIT_APPLE',
                         'FRUIT_GREEN_BOOB',
                         'FRUIT_SPACESHIP',
                         'FRUIT_BELL',
                         'FRUIT_KEY',
                         'WALL_GHOST',
                         'WALL_L_UP_LEFT',
                         'WALL_L_UP',
                         'WALL_L_UP_RIGHT',
                         'WALL_L_LEFT',
                         'WALL_L',
                         'WALL_L_RIGHT',
                         'WALL_L_DOWN_LEFT',
                         'WALL_L_DOWN',
                         'WALL_L_DOWN_RIGHT',
                         'WALL_LC_UP_LEFT',
                         'WALL_LC_UP_RIGHT',
                         'WALL_LC_UP_LEFT_RIGHT',
                         'WALL_LC_DOWN_LEFT',
                         'WALL_LC_DOWN_RIGHT',
                         'WALL_LC_DOWN_LEFT_RIGHT',
                         'WALL_LC_UP_DOWN_LEFT',
                         'WALL_LC_UP_DOWN_RIGHT',
                         'WALL_LC_UP_DOWN_LEFT_RIGHT',
                         'WALL_S_UP_LEFT',
                         'WALL_S_UP_RIGHT',
                         'WALL_S_DOWN_LEFT',
                         'WALL_S_DOWN_RIGHT',
                         'WALL_S_UP_DOWN_LEFT',
                         'WALL_S_UP_DOWN_RIGHT',
                         'WALL_S_DOWN_LEFT_RIGHT',
                         'WALL_S_UP_LEFT_RIGHT',
                         'WALL_S_LEFT',
                         'WALL_S_RIGHT',
                         'WALL_S_LEFT_RIGHT',
                         'WALL_S_UP',
                         'WALL_S_DOWN',
                         'WALL_S_UP_DOWN',
                         'WALL_S',
                         'WALL_SL_UP_LEFT',
                         'WALL_SL_UP_RIGHT',
                         'WALL_SL_DOWN_LEFT',
                         'WALL_SL_DOWN_RIGHT',
                         'WALL_SL_LEFT_UP',
                         'WALL_SL_LEFT_DOWN',
                         'WALL_SL_RIGHT_UP',
                         'WALL_SL_RIGHT_DOWN'])

WALLS_NO_GHOST = [TILEID.WALL_L_UP_LEFT,
                  TILEID.WALL_L_UP,
                  TILEID.WALL_L_UP_RIGHT,
                  TILEID.WALL_L_LEFT,
                  TILEID.WALL_L,
                  TILEID.WALL_L_RIGHT,
                  TILEID.WALL_L_DOWN_LEFT,
                  TILEID.WALL_L_DOWN,
                  TILEID.WALL_L_DOWN_RIGHT,
                  TILEID.WALL_LC_UP_LEFT,
                  TILEID.WALL_LC_UP_RIGHT,
                  TILEID.WALL_LC_UP_LEFT_RIGHT,
                  TILEID.WALL_LC_DOWN_LEFT,
                  TILEID.WALL_LC_DOWN_RIGHT,
                  TILEID.WALL_LC_DOWN_LEFT_RIGHT,
                  TILEID.WALL_LC_UP_DOWN_LEFT,
                  TILEID.WALL_LC_UP_DOWN_RIGHT,
                  TILEID.WALL_LC_UP_DOWN_LEFT_RIGHT,
                  TILEID.WALL_S_UP_LEFT,
                  TILEID.WALL_S_UP_RIGHT,
                  TILEID.WALL_S_DOWN_LEFT,
                  TILEID.WALL_S_DOWN_RIGHT,
                  TILEID.WALL_S_UP_DOWN_LEFT,
                  TILEID.WALL_S_UP_DOWN_RIGHT,
                  TILEID.WALL_S_DOWN_LEFT_RIGHT,
                  TILEID.WALL_S_UP_LEFT_RIGHT,
                  TILEID.WALL_S_LEFT,
                  TILEID.WALL_S_RIGHT,
                  TILEID.WALL_S_LEFT_RIGHT,
                  TILEID.WALL_S_UP,
                  TILEID.WALL_S_DOWN,
                  TILEID.WALL_S_UP_DOWN,
                  TILEID.WALL_S,
                  TILEID.WALL_SL_UP_LEFT,
                  TILEID.WALL_SL_UP_RIGHT,
                  TILEID.WALL_SL_DOWN_LEFT,
                  TILEID.WALL_SL_DOWN_RIGHT,
                  TILEID.WALL_SL_LEFT_UP,
                  TILEID.WALL_SL_LEFT_DOWN,
                  TILEID.WALL_SL_RIGHT_UP,
                  TILEID.WALL_SL_RIGHT_DOWN]

WALLS = WALLS_NO_GHOST.copy()
WALLS.append(TILEID.WALL_GHOST)

DIRECTION = [(-1, 0), (0, 1), (1, 0), (0, -1)]
DIR_NAMES = {(-1, 0): 'LEFT', (0, 1): 'DOWN', (1, 0): 'RIGHT', (0, -1): 'UP', (0, 0): 'RIGHT'}
